// AUTHENTICATION ACTIONS
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGOUT = "LOGOUT";

// DATING ACTIONS
export const GET_TAGS_START = "GET_TAGS_START";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAILED = "GET_TAGS_FAILED";

export const ADD_TAG_START = "ADD_TAG_START";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_FAILED = "ADD_TAG_FAILED";

export const DELETE_TAG_START = "DELETE_TAG_START";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_FAILED = "DELETE_TAG_FAILED";