// AUTHENTICATION ACTIONS
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGOUT = "LOGOUT";

// DATING ACTIONS
export const DATING_REQUEST_START = "DATING_REQUEST_START";
export const DATING_REQUEST_FAILED = "DATING_REQUEST_FAILED";


export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";


export const ADD_PROFILEPHOTO_SUCCESS = "ADD_PROFILEPHOTO_SUCCESS";
export const GET_PROFILEPHOTOS_SUCCESS = "GET_PROFILEPHOTOS_SUCCESS";
export const DELETE_PROFILEPHOTO_SUCCESS = "DELETE_PROFILEPHOTO_SUCCESS";
export const SET_MAIN_PROFILEPHOTO_SUCCESS = "SET_MAIN_PROFILEPHOTO_SUCCESS";

export const GET_DATINGPROFILE_SUCCESS = "GET_DATINGPROFILE_SUCCESS";