const SESSION_SECRET_KEY = "FFFFFFF";
const TOKEN_SECRET_KEY = "FFFFFFF";

const DATABASE_NAME = "maitTalks";
const DATABASE_USERNAME = "maitTalksAdmin";
const DATABASE_PASSWORD = "123456";

module.exports = {
    SESSION_SECRET_KEY,
    TOKEN_SECRET_KEY,
    DATABASE_NAME,
    DATABASE_PASSWORD,
    DATABASE_USERNAME
}